### ISSUE TITLE
GNSS Analysis App Matlab source code

### ISSUE THREAD

**Issue by binghy** [DfAC/AndroidGNSS#6]
Hi, hope not to bother you, but I was wondering if the complete Matlab source code of the GNSS Analysis App is free and available. The one that I've found here and in the official repository regards the basic processing, I was interested (I repeat, if it's open source and available) in the code running under the GNSS Analysis App, providing processing of data coming from all the constellations recorded in the log and, most of all, doppler smoothing of the code (as described in the GSA White Paper that I've found online). I've seen that, for example, in the GpsWlsPvt.m Matlab script, there is only a line specyfing the parameter gnssMeas.PrSmM (and its standard deviation), but in the complete project it seems to me there is no other reference. Am I correct?

Thanks in advance
 
Francesco

**Comment by DfAC** [comment]
Hi Francesco,
GNSS Analysis App is maintained by Google. As you might have noticed not everything is available. The results in the GSA White Paper have been produced using additional code, which unfortunately cannot be made available at this stage. We are working to make it open source.

**Comment by binghy** [comment]
thank you for replying me. Do you know when it'll be available?

**Comment by DfAC** [comment]
Unfortunately not

**Comment by DfAC** [comment]
Hi Francesco - is this <https://github.com/google/gps-measurement-tools/archive/V2.5.0.0.zip> of any help to you?

**Comment by binghy** [comment]
Hi, is this not the same old one version? It seems to me there are no updates about the variables gnssMeas.PrSmM and its standard deviation

**Comment by DfAC** [comment]
Yes. You are correct. Nothing was released then. Apologies for false hope.
