### ISSUE TITLE
Galileo "received sv time filed"

### ISSUE THREAD

**Issue by dadawang** [DfAC/AndroidGNSS#7]
Hi, I am trying to calculate Galileo pseudorange following your python jupyter notebook, but the Galileo pseudorange results is at the "1e14" scale, due to the very small "received sv time filed" at the milliseconds level. Am i Missing some time offset comparing to GPS time? Thanks for your time.

**Comment by DfAC** [comment]
Hey Dadang,
Galileo time should be almost the same as GPS time (check page 10 of GSA whitepaper at <https://www.gsa.europa.eu/system/files/reports/gnss_raw_measurement_web_0.pdf>). I know some phones have problems with distinguishing between Galileo and Beudou signal as they operate from same frequency. What phone are you using?

And apologies for late reply - I am away from the office most of March and April

**Comment by DfAC** [comment]
Is your phone P10?
